In [1]:
import pandas as pd

In [4]:
df = pd.read_excel("../data/salesList.xlsx")

In [5]:
df

,伝票NO,日付,顧客コード,顧客名,商品コード,商品名,数量,単価,金額
0,1010981,2022-11-15,1,赤坂次郎,M2000123004,プロティンパウダー(イチゴ),10,1700,17000
1,1010981,2022-11-15,1,赤坂次郎,W1100001202,ヨガマットM,2,6000,12000
2,1010982,2022-11-16,2,大手町茜,W1200001201,タンクトップS,1,2000,2000
3,1010982,2022-11-16,2,大手町茜,M2000123006,プロティンパウダー(ソイ),2,1700,3400
4,1010983,2022-12-01,11,妻夫木淳寛,M2000123001,ストレッチバンドS,1,1500,1500
5,1010983,2022-12-01,11,妻夫木淳寛,M2000123002,トレニーングチューブ,1,1800,1800
6,1010983,2022-12-01,11,妻夫木淳寛,M2000123003,バランスボール,1,3800,3800
7,1020765,2022-11-20,5,軽井佐和男,W1200001202,タンクトップM,1,2000,2000
8,1020765,2022-11-20,5,軽井佐和男,M1000043002,ポロシャツM,1,2100,2100
9,1020765,2022-11-20,5,軽井佐和男,M1000043002,TシャツM,1,2500,2500
10,1020766,2022-11-23,4,大阪太郎,M2000123004,プロティンパウダー(イチゴ),5,1700,8500
11,1020766,2022-11-23,4,大阪太郎,M2000123005,プロティンパウダー(コーヒー),5,1700,8500
12,1020767,2022-11-20,8,友田芽依,M2000123001,ストレッチバンドS,1,1500,1500
13,1020767,2022-11-20,8,友田芽依,M2000123002,トレニーングチューブ,2,1800,3600
14,1020767,2022-11-20,8,友田芽依,M2000123003,バランスボール,1,3800,3800
15,1024001,2022-11-20,10,帳達夫,M2000123001,ストレッチバンドS,1,1500,1500
16,1024001,2022-11-20,10,帳達夫,M2000123002,トレニーングチューブ,2,1800,3600
17,1024001,2022-11-20,10,帳達夫,M2000123004,プロティンパウダー(イチゴ),5,1700,8500
18,1024002,2022-11-24,9,木村雀士,W1100001203,ヨガマットL,1,8000,8000
19,1024002,2022-11-24,9,木村雀士,M1000043005,TシャツXL,2,2500,5000
20,1024003,2022-12-01,1,赤坂次郎,M2000123004,プロティンパウダー(イチゴ),10,1700,17000
21,1024004,2022-12-02,5,軽井佐和男,M2000123001,ストレッチバンドS,1,1500,1500
22,1024004,2022-12-02,5,軽井佐和男,M2000123002,トレニーングチューブ,1,1800,1800
23,1024005,2022-12-05,9,木村雀士,M2000123005,プロティンパウダー(コーヒー),2,1700,3400
24,1024005,2022-12-05,9,木村雀士,M2000123006,プロティンパウダー(ソイ),3,1700,5100
25,1024006,2022-12-05,4,大阪太郎,M2000123004,プロティンパウダー(イチゴ),5,1700,8500
26,1024006,2022-12-05,4,大阪太郎,M2000123005,プロティンパウダー(コーヒー),5,1700,8500
27,1024007,2022-12-15,1,赤坂次郎,M2000123004,プロティンパウダー(イチゴ),10,1700,17000
28,1024008,2022-12-15,2,大手町茜,M2000123006,プロティンパウダー(ソイ),3,1700,5100

In [6]:
df["金額"].mean()

5810.3448275862065

In [8]:
df.groupby("顧客名").size()

顧客名
友田芽依      3
大手町茜      3
大阪太郎      4
妻夫木淳寛　    3
帳達夫       3
木村雀士      4
赤坂次郎      4
軽井佐和男     5
dtype: int64

In [9]:
df[["顧客名","金額"]].groupby("顧客名").mean()

                  金額
顧客名
友田芽依     2966.666667
大手町茜     3500.000000
大阪太郎     8500.000000
妻夫木淳寛　   2366.666667
帳達夫      4533.333333
木村雀士     5375.000000
赤坂次郎    15750.000000
軽井佐和男    1980.000000

In [10]:
df[["顧客名","商品名","金額"]].groupby(["顧客名","商品名"]).sum()

                           金額
顧客名    商品名
友田芽依   ストレッチバンドS         1500
       トレニーングチューブ        3600
       バランスボール           3800
大手町茜   タンクトップS           2000
       プロティンパウダー(ソイ)     8500
大阪太郎   プロティンパウダー(イチゴ)   17000
       プロティンパウダー(コーヒー)  17000
妻夫木淳寛　 ストレッチバンドS         1500
       トレニーングチューブ        1800
       バランスボール           3800
帳達夫    ストレッチバンドS         1500
       トレニーングチューブ        3600
       プロティンパウダー(イチゴ)    8500
木村雀士   TシャツXL            5000
       プロティンパウダー(コーヒー)   3400
       プロティンパウダー(ソイ)     5100
       ヨガマットL            8000
赤坂次郎   プロティンパウダー(イチゴ)   51000
       ヨガマットM           12000
軽井佐和男  TシャツM             2500
       ストレッチバンドS         1500
       タンクトップM           2000
       トレニーングチューブ        1800
       ポロシャツM            2100

In [11]:
df[["商品名","金額"]].groupby(["商品名"]).max()

                    金額
商品名
TシャツM             2500
TシャツXL            5000
ストレッチバンドS         1500
タンクトップM           2000
タンクトップS           2000
トレニーングチューブ        3600
バランスボール           3800
プロティンパウダー(イチゴ)   17000
プロティンパウダー(コーヒー)   8500
プロティンパウダー(ソイ)     5100
ポロシャツM            2100
ヨガマットL            8000
ヨガマットM           12000

In [13]:
df[["商品名","単価","金額"]].groupby(["商品名"]).agg({"商品名":"count","単価":"max","金額":"sum"})

                 商品名    単価     金額
商品名
TシャツM              1  2500   2500
TシャツXL             1  2500   5000
ストレッチバンドS          4  1500   6000
タンクトップM            1  2000   2000
タンクトップS            1  2000   2000
トレニーングチューブ         4  1800  10800
バランスボール            2  3800   7600
プロティンパウダー(イチゴ)     6  1700  76500
プロティンパウダー(コーヒー)    3  1700  20400
プロティンパウダー(ソイ)      3  1700  13600
ポロシャツM             1  2100   2100
ヨガマットL             1  8000   8000
ヨガマットM             1  6000  12000