In [3]:
import pandas as pd

In [4]:
df = pd.read_excel("../data/salesList.xlsx")

In [5]:
df.tail()

,伝票NO,日付,顧客コード,顧客名,商品コード,商品名,数量,単価,金額
24,1024005,2022-12-05,9,木村雀士,M2000123006,プロティンパウダー(ソイ),3,1700,5100
25,1024006,2022-12-05,4,大阪太郎,M2000123004,プロティンパウダー(イチゴ),5,1700,8500
26,1024006,2022-12-05,4,大阪太郎,M2000123005,プロティンパウダー(コーヒー),5,1700,8500
27,1024007,2022-12-15,1,赤坂次郎,M2000123004,プロティンパウダー(イチゴ),10,1700,17000
28,1024008,2022-12-15,2,大手町茜,M2000123006,プロティンパウダー(ソイ),3,1700,5100

In [6]:
df.pivot_table(index="商品名", columns="顧客名", values="金額", margins=True, aggfunc="sum")

顧客名,友田芽依,大手町茜,大阪太郎,妻夫木淳寛,帳達夫,木村雀士,赤坂次郎,軽井佐和男,All
商品名,,,,,,,,,
TシャツM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2500.0,2500
TシャツXL,NaN,NaN,NaN,NaN,NaN,5000.0,NaN,NaN,5000
ストレッチバンドS,1500.0,NaN,NaN,1500.0,1500.0,NaN,NaN,1500.0,6000
タンクトップM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,2000
タンクトップS,NaN,2000.0,NaN,NaN,NaN,NaN,NaN,NaN,2000
トレニーングチューブ,3600.0,NaN,NaN,1800.0,3600.0,NaN,NaN,1800.0,10800
バランスボール,3800.0,NaN,NaN,3800.0,NaN,NaN,NaN,NaN,7600
プロティンパウダー(イチゴ),NaN,NaN,17000.0,NaN,8500.0,NaN,51000.0,NaN,76500
プロティンパウダー(コーヒー),NaN,NaN,17000.0,NaN,NaN,3400.0,NaN,NaN,20400
プロティンパウダー(ソイ),NaN,8500.0,NaN,NaN,NaN,5100.0,NaN,NaN,13600
ポロシャツM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2100.0,2100
ヨガマットL,NaN,NaN,NaN,NaN,NaN,8000.0,NaN,NaN,8000
ヨガマットM,NaN,NaN,NaN,NaN,NaN,NaN,12000.0,NaN,12000
All,8900.0,10500.0,34000.0,7100.0,13600.0,21500.0,63000.0,9900.0,168500

In [7]:
df.pivot_table(index="商品名", columns="顧客名", values="金額", fill_value=0, margins=True, aggfunc="sum")

顧客名,友田芽依,大手町茜,大阪太郎,妻夫木淳寛,帳達夫,木村雀士,赤坂次郎,軽井佐和男,All
商品名,,,,,,,,,
TシャツM,0,0,0,0,0,0,0,2500,2500
TシャツXL,0,0,0,0,0,5000,0,0,5000
ストレッチバンドS,1500,0,0,1500,1500,0,0,1500,6000
タンクトップM,0,0,0,0,0,0,0,2000,2000
タンクトップS,0,2000,0,0,0,0,0,0,2000
トレニーングチューブ,3600,0,0,1800,3600,0,0,1800,10800
バランスボール,3800,0,0,3800,0,0,0,0,7600
プロティンパウダー(イチゴ),0,0,17000,0,8500,0,51000,0,76500
プロティンパウダー(コーヒー),0,0,17000,0,0,3400,0,0,20400
プロティンパウダー(ソイ),0,8500,0,0,0,5100,0,0,13600
ポロシャツM,0,0,0,0,0,0,0,2100,2100
ヨガマットL,0,0,0,0,0,8000,0,0,8000
ヨガマットM,0,0,0,0,0,0,12000,0,12000
All,8900,10500,34000,7100,13600,21500,63000,9900,168500

In [8]:
df.pivot_table(index="顧客名", columns="商品名", values="金額", fill_value=0, margins=True, aggfunc="mean")

商品名,TシャツM,TシャツXL,ストレッチバンドS,タンクトップM,タンクトップS,トレニーングチューブ,バランスボール,プロティンパウダー(イチゴ),プロティンパウダー(コーヒー),プロティンパウダー(ソイ),ポロシャツM,ヨガマットL,ヨガマットM,All
顧客名,,,,,,,,,,,,,,
友田芽依,0,0,1500,0,0,3600,3800,0,0,0.000000,0,0,0,2966.666667
大手町茜,0,0,0,0,2000,0,0,0,0,4250.000000,0,0,0,3500.000000
大阪太郎,0,0,0,0,0,0,0,8500,8500,0.000000,0,0,0,8500.000000
妻夫木淳寛,0,0,1500,0,0,1800,3800,0,0,0.000000,0,0,0,2366.666667
帳達夫,0,0,1500,0,0,3600,0,8500,0,0.000000,0,0,0,4533.333333
木村雀士,0,5000,0,0,0,0,0,0,3400,5100.000000,0,8000,0,5375.000000
赤坂次郎,0,0,0,0,0,0,0,17000,0,0.000000,0,0,12000,15750.000000
軽井佐和男,2500,0,1500,2000,0,1800,0,0,0,0.000000,2100,0,0,1980.000000
All,2500,5000,1500,2000,2000,2700,3800,12750,6800,4533.333333,2100,8000,12000,5810.344828

In [9]:
df.pivot_table(index="商品名", columns="顧客名", values="金額", fill_value=0, margins=True, aggfunc=["count","sum"])

                count                                            sum         \
顧客名              友田芽依 大手町茜 大阪太郎 妻夫木淳寛　 帳達夫 木村雀士 赤坂次郎 軽井佐和男 All  友田芽依   大手町茜
商品名
TシャツM               0    0    0      0   0    0    0     1   1     0      0
TシャツXL              0    0    0      0   0    1    0     0   1     0      0
ストレッチバンドS           1    0    0      1   1    0    0     1   4  1500      0
タンクトップM             0    0    0      0   0    0    0     1   1     0      0
タンクトップS             0    1    0      0   0    0    0     0   1     0   2000
トレニーングチューブ          1    0    0      1   1    0    0     1   4  3600      0
バランスボール             1    0    0      1   0    0    0     0   2  3800      0
プロティンパウダー(イチゴ)      0    0    2      0   1    0    3     0   6     0      0
プロティンパウダー(コーヒー)     0    0    2      0   0    1    0     0   3     0      0
プロティンパウダー(ソイ)       0    2    0      0   0    1    0     0   3     0   8500
ポロシャツM              0    0    0      0   0    0    0     1   1     0      0
ヨガマットL              0    0    0      0   0    1    0     0   1     0      0
ヨガマットM              0    0    0      0   0    0    1     0   1     0      0
All                 3    3    4      3   3    4    4     5  29  8900  10500


顧客名               大阪太郎 妻夫木淳寛　    帳達夫   木村雀士   赤坂次郎 軽井佐和男     All
商品名
TシャツM                0      0      0      0      0  2500    2500
TシャツXL               0      0      0   5000      0     0    5000
ストレッチバンドS            0   1500   1500      0      0  1500    6000
タンクトップM              0      0      0      0      0  2000    2000
タンクトップS              0      0      0      0      0     0    2000
トレニーングチューブ           0   1800   3600      0      0  1800   10800
バランスボール              0   3800      0      0      0     0    7600
プロティンパウダー(イチゴ)   17000      0   8500      0  51000     0   76500
プロティンパウダー(コーヒー)  17000      0      0   3400      0     0   20400
プロティンパウダー(ソイ)        0      0      0   5100      0     0   13600
ポロシャツM               0      0      0      0      0  2100    2100
ヨガマットL               0      0      0   8000      0     0    8000
ヨガマットM               0      0      0      0  12000     0   12000
All              34000   7100  13600  21500  63000  9900  168500